<?php include 'includes/_head.php'; ?>

		<div id="wrap">
			
			<?php include 'includes/_header.php'; ?>
			
			<div id="content">
					
				<div class="section">
					<div class="inner">
						<h1>Privacy Policy</h1>
						<p class="text-center">Last updated: 4/23/15</p>
						<p>Bringhub, Inc. ("Bringhub") values your privacy. In this Privacy Policy ("Policy"), we describe how we collect, use, and disclose information that we obtain through our website www.bringhub.com (the "Site") and the services available through our Site, as well as the bringhub shopping cart (collectively, the "Services").</p>
<p>By visiting the Site, or using any of our Services, you agree that your personal information will be handled as described in this Policy. Your use of our Site or Services, and any dispute over privacy, is subject to this Policy and our Terms of Use, available at [URL], including its applicable limitations on damages and the resolution of disputes. The Bringhub Terms of Use are incorporated by reference into this Policy.</p>

<h3>WHAT INFORMATION DO WE COLLECT ABOUT YOU AND WHY?</h3>
<p>We may collect information about you directly from you and from third parties, as well as automatically through your use of our Site or Services.</p>
<p>Information We Collect Directly From You. You may browse certain areas of our Site and use some of our Services without registering. However, to access certain Services, we may require you to, or give you the option of registering. To register you must provide your email, phone number, first and last name, shipping address, and create a password. We also may collect additional optional information from you, including payment information (including credit card information and billing information) to be used for later, and additional optional information; however, you are not required to provide us with this information to register. In addition, if you make a purchase using our Services, we will also request that you provide your credit or debit card information, payment information, and your billing and shipping address, and if you are a registered user you can save this information to your account.</p>
<p>Your Activities. If you post comments, such as to a blog or in other areas of the Site, or other content (e.g., videos, pictures) we collect information about that content. In addition, if you send us communications through the Site or via email, we collect information about your communications with us. We also collect information about the items you add to your cart, what products you view, pages you click and the images you view that are available for purchase through Bringhub on our partner sites, as well as the information described under Information We Collect Automatically.</p>
<p>Information We Receive from Third Parties. You may also log in to the Services and register with us using your Facebook or Twitter account. To login through Facebook, you must grant us permission to collect your Facebook email, friends list and basic information, as well as any other information stated on the permissions page. To login using Twitter, you must grant us access to your Twitter registered email address and allow us to read Tweets from your timeline and see whom you follow. These third party sites may grant us access to your information on an ongoing basis. We store the information that we receive from these sites with other information that we collect from you or receive about you. These third party sites control the information they collect from and share about you. For information about they may use and disclose your information, including any information you make public, please consult their respective privacy policies.</p>
<p>Information We Collect Automatically. We may automatically collect the following information about your use of our Site or Services through cookies, web beacons, log files, java script and other technologies: your domain name; your browser type and operating system; web pages you view; links you click; your IP address; the length of time you visit our Site and or use our Services; your location information; and the referring URL, or the webpage that led you to our Site; access time; and a device identifier. In addition, we may collect information about the pages, products and content you view on sites of our partners. We may combine this information with other information that we have collected about you, including, where applicable, your user name, name, and other personal information Please see the section "Cookies and Other Tracking Mechanisms" below for more information.</p>
<h3>HOW WE USE YOUR INFORMATION</h3>
<p>We use your information, including your personal information, for the following purposes:</p>
<ul class="styled">
<li>To provide our Services to you, to communicate with you about your use of our Services, to respond to your inquiries, to fulfill your orders with retailers, and for other customer service purposes.</li>
<li>To tailor the content and information that we may send or display to you, to offer location customization, and personalized help and instructions, and to otherwise personalize your experiences while using the Site or our Services. We also may use the information that we learn about you to assist us in advertising our Services on third party websites, and advertising third party products and services on our Site.</li>
<li>For marketing and promotional purposes. For example, we may use your information, such as your email address, to send you news and newsletters, special offers, and promotions, or to otherwise contact you about products or information we think may interest you.</li>
<li>To better understand how users access and use our Site and Services, both on an aggregated and individualized basis, in order to improve our Site and Services, respond to user desires and preferences, and for other research and analytical purposes (such as analyzing and composing reports on trends).</li>
</ul>
<h3>HOW WE SHARE YOUR INFORMATION</h3>
<p>Our Services permit you to purchase a product you see on one of our partners' websites ("Publishers"), directly from a retailer ("Retailer") who sells that product. In this section we explain why and with whom we share your information:</p>

<p>Retailers. Our Services allow you to purchase products from a wide variety of merchants, directly from the Publisher's website where you spotted the product. To facilitate your purchase from a Retailer, we may share certain personal information with that Retailer, including your name, contact information, payment information and billing and shipping address. The use of your information by the Retailer is subject to the Retailer's own privacy policy and purchase terms; we recommend that you review these policies prior to making a purchase.</p>
<p>Publishers. We may share certain information about your activities on a Publisher's website, with that Publisher, including the products you purchased, items you added to your cart, images you viewed or other activities on that Publisher's site, as well as your name and contact (email, phone and address) information. We will not share your credit card information with a Publisher.</p>
<p>Bringhub Users. Your user name and any information that you post to our Site or Services, including product reviews and comments, will be available to and searchable by other users.</p>
<p>Affiliates. We may disclose the information we collect from you to our affiliates or subsidiaries; however, if we do so, their use and disclosure of your personally identifiable information will be subject to this Policy.</p>
<p>Service Providers. We may disclose the information we collect from you to third party vendors, service providers, contractors or agents who perform functions on our behalf.</p>
<p>Business Transfers. If we are acquired by or merged with another company, if substantially all of our assets are transferred to another company, or as part of a bankruptcy proceeding, we may transfer the information we have collected from you to the other company.</p>
<p>In Response to Legal Process. We also may disclose the information we collect from you in order to comply with the law, a judicial proceeding, court order, or other legal process, such as in response to a court order or a subpoena.</p>
<p>To Protect Us and Others. We also may disclose the information we collect from you where we believe it is necessary to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the safety of any person, violations of our Terms of Use or this Policy, or as evidence in litigation in which Bringhub is involved.</p>
<p>Aggregate and De-Identified Information. We may share aggregate or de-identified information about users with third parties for marketing, advertising, research or similar purposes.</p>
<h3>OUR USE OF COOKIES AND OTHER TRACKING MECHANISMS</h3>
<p>We and our third party service providers use cookies and other tracking mechanisms to track information about your use of our Site and Services. We may combine this information with other personal information we collect from you (and our third party service providers may do so on our behalf). Currently, our systems do not recognize browser "do-not-track" requests. You may, however, disable certain tracking as discussed in this section (e.g., by disabling cookies).</p>
<p>Cookies. Cookies are alphanumeric identifiers that we transfer to your computer's hard drive through your web browser for record-keeping purposes. Some cookies allow us to make it easier for you to navigate our Site and services, while others are used to enable a faster log-in process or to allow us to track your activities at our Site and Service. Most web browsers automatically accept cookies, but if you prefer, you can edit your browser options to block them in the future. The Help portion of the toolbar on most browsers will tell you how to prevent your computer from accepting new cookies, how to have the browser notify you when you receive a new cookie, or how to disable cookies altogether. Visitors to our Site who disable cookies will be able to browse certain areas of the Site, but some features may not function.</p>
<p>Clear GIFs, pixel tags and other technologies. Clear GIFs are tiny graphics with a unique identifier, similar in function to cookies. In contrast to cookies, which are stored on your computer's hard drive, clear GIFs are embedded invisibly on web pages. We may use clear GIFs (also known as web beacons, web bugs or pixel tags), in connection with our Site to, among other things, track the activities of Site visitors, help us manage content and compile statistics about Site usage. We or our service providers may also use clear GIFs in HTML emails to our customers to help us track email response rates, identify when our emails are viewed and track whether our emails are forwarded.</p>
<p>Third-party Analytics. We use third party analytics tools, including Google Analytics, to collect, monitor and analyze this information in order to improve functionality and user-friendliness, and to better tailor the Site and Services to our visitors' needs. Accordingly, usage data is shared with Google, which has its own privacy policy addressing how it uses such information. We encourage you to review this privacy policy to understand how Google uses such information.</p>
<h3>USER GENERATED CONTENT</h3>
<p>We may invite you to post content on our Site or Services, including your comments, reviews, pictures, and any other information. If you post such content, all of the information that you post will be available to other users of our Site and Services. Your posting may become public and Bringhub cannot prevent such information from being used in a manner that may violate this Policy, the law, or your personal privacy.</p>
<h3>PLUG-INS AND SOCIAL MEDIA WIDGETS</h3>
<p>Our Site and Service may include social media features and widgets, such as the Facebook Like button and the "Share this" button, as well as other interactive mini-programs that run on our Site and Services and enable certain features to work (e.g., blogs and comments). These features may collect your IP address, which page you are visiting on our Site or viewing through the Services, and may set a cookie to enable the feature to function properly and for other purposes. These features are displayed on our Site, but are hosted by third parties, and are subject to their own privacy policies, not this one. Your interactions with these features are governed by the privacy policy of the company providing them</p>
<h3>THIRD-PARTY LINKS</h3>
<p>Our Site and Services may contain links to third-party websites. Any access to and use of such linked websites is not governed by this Policy, but instead is governed by the privacy policies of those third party websites. We are not responsible for the information practices of such third party websites. In addition, our Publishers and Retailers have their own privacy policies, and their use and disclosure of your personal information is subject to their own privacy policies, not this one.</p>
<h3>SECURITY OF MY PERSONAL INFORMATION	</h3>
<p>We have implemented safeguards to protect the information we collect from unauthorized access, use, and disclosure. Please be aware that despite our best efforts, no data security measures can guarantee 100% security. You should take steps to protect against unauthorized access to your password, phone, and computer by, among other things, signing off after using a shared computer, choosing a robust password that nobody else knows or can easily guess, and keeping your log-in and password private. We are not responsible for any lost, stolen, or compromised passwords or for any activity on your account via unauthorized password activity.</p>
<h3>ACCESS TO MY PERSONAL INFORMATION</h3>
<p>You may modify personal information that you have submitted by logging into your account and updating your profile information. Please note that copies of information that you have updated, modified or deleted may remain viewable in cached and archived pages of the Site for a period of time, and we may maintain copies of such information in our business records.</p>
<h3>WHAT CHOICES DO I HAVE REGARDING USE OF MY PERSONAL INFORMATION?</h3>
<p>We may send periodic promotional or informational emails to you, about Bringhub and the Services, and, from time-to-time, about third party products and offers we think may interest you. You may opt-out of such communications by following the opt-out instructions contained in the e-mail. Please note that it may take up to 10 business days for us to process opt-out requests. If you opt-out of receiving promotional emails from us, we may still send you e-mails about your account or any Services you have requested or received from us. Also, please note that if you take advantage of a third party offer that Bringhub has sent to you, that third party may collect certain information from you, subject to their own privacy policy.</p>
<h3>CHILDREN UNDER 13</h3>
<p>Our Services are not designed for children under 13. If we discover that a child under 13 has provided us with personal information, we will delete such information from our systems.</p>
<h3>SPECIAL INFORMATION FOR CALIFORNIA CONSUMERS</h3>
<p>California residents may request a list of certain third parties to which we have disclosed personally identifiable information about you for their own direct marketing purposes. You may make one request per calendar year. In your request, please attest to the fact that you are a California resident and provide a current California address for your response. You may request this information in writing by contacting us at: <a href="mailto:privacy@bringhub.com">privacy@bringhub.com</a>. Please allow up to thirty (30) days for a response.</p>
<h3>CONTACT US</h3>
<p>If you have questions about the privacy aspects of our Services or would like to make a complaint, please contact us at <a href="mailto:privacy@bringhub.com">privacy@bringhub.com</a>.</p>
<h3>CHANGES TO THIS POLICY</h3>
<p>This Policy is current as of the Last Updated Date set forth above. We may change this Policy from time to time, so please be sure to check back periodically. We will post any changes to this Policy on our Site or Services, at <a href="http://www.bringhub.com/#!privacypolicy/c1604">http://www.bringhub.com/#!privacypolicy/c1604</a>. If we make any changes to this Policy that materially affect our practices with regard to the personal information we have previously collected from you, we will endeavor to provide you with notice in advance of such change by highlighting the change on our Site, or by emailing your email address of record.</p>
					</div>
				</div>


			<?php include 'includes/_footer.php'; ?>	
		</div>

<?php include 'includes/_foot.php'; ?>
