<?php include 'includes/_head.php'; ?>

		<div id="wrap">
			
			<?php include 'includes/_header.php'; ?>
			
			<div id="content">
					
				<div class="section">
					<div class="inner">
						<h1>Terms of Service</h1>
						<p class="text-center">Last updated: 5/5/15</p>
						

		<p>These Terms of Use ("Terms") are a legal contract between Bringhub Inc. ("Bringhub" or "Us" or "Our" or "We")  and You (collectively, "Everyone") and govern Your use of all the text, data, information, software, instructions, application programming interface, applications, graphics, photographs and more (all of which We refer to as "Materials") that We and Our affiliates may make available to You, as well as any services ("Services") We may provide through any of Our websites (all of which are referred to in these Terms as this "Website"). Unless otherwise specified, all references to "Website" include any software that We may provide to you that allow access to the Services from a mobile device (a "Mobile Application").  </p>
		<p>READ THESE TERMS CAREFULLY BEFORE BROWSING THIS WEBSITE AND/OR REGISTERING FOR SERVICES.  USING THIS WEBSITE OR THE SERVICES INDICATES THAT YOU HAVE BOTH READ AND ACCEPT THESE TERMS.  YOU CANNOT USE THIS WEBSITE  OR THE SERVICES IF YOU DO NOT ACCEPT THESE TERMS.  </p>
		<h3>I. WHAT WE DO AND CHANGES TO SERVICES AND TERMS.</h3>
		<p>Our Services are provided through the Website (which includes Mobile Applications) which is a platform that allows consumers to buy directly from Retailers when looking at content in a Publisher's site.</p>
		<p>We may alter and/or choose to modify, suspend or discontinue the Website, the Materials or the Services (collectively, the "Bringhub Platform") at any time, without notice. If you object to any changes to the Bringhub Platform your sole recourse will be to cease using it. Continued use of the Bringhub Platform following posting of any such changes will indicate your acknowledgement of such changes and satisfaction with the Bringhub Platform as so modified. We will not be liable to you or any third-party should we exercise our right to modify or discontinue the Bringhub Platform. </p>
		<p>We can change, update, or add or remove provisions of these Terms, at any time by posting the updated Terms on this Website and by providing a notice on the Website. By using this Website after We have updated the Terms, you are agreeing to all the updated Terms; if you do not agree with any of the updated Terms, you must stop using the Website.  </p>
		<p>In addition, certain features of the Services may be subject to additional terms of use. By using such features, or any part thereof, you agree to be bound by the additional terms of use applicable to such features. In the event that any of the additional terms of use governing such area conflict with these Terms, the additional terms will govern.  If expressly incorporated, these terms will apply in addition to separately executed written agreements, however in the event of a conflict between these Terms and a separately executed written agreement, the separately executed written agreement will govern.  </p>
		<h3>II.  PRIVACY</h3>
		<p>We respect the information that You provide to Us, and want to be sure You fully understand exactly how We use that information.  So, please review Our  <a href="/privacy-policy">Privacy Policy</a> ("Privacy Policy") which explains our privacy practices and which forms an integral part of these Terms. If you use the Services and/or the Website, and/or if you register for any programs or accounts, you are accepting our <a href="/privacy-policy">Privacy Policy</a>, as may be amended from time to time. If you do not agree to have your information used in any of the ways described in the Privacy <a href="/privacy-policy">Privacy Policy</a>, you must discontinue use of the Site and the Services.</p>
		<h3>III.  VISITORS AND REGISTERED USERS</h3>
		<h4>(a) Visitors</h4>
		<p>As a "Visitor", you can view, visit and browse through the Website.  You need not register with Bringhub to simply visit and view the Website, to browse and see the partial, publicly accessible information in the Website.</p>
		<p>However, in order to access the Services and Materials offered on and through the Website, you must register with Bringhub to contract the Services,  and to receive an account and a password.  Registered Users can contract as Retailers or Publishers, or can access some services as Consumers.   </p>
		<h4>(b) Password Restricted Areas of this Website</h4>
			<p>(i) Publishers means entities that are providers of, or host, online content which Consumers can choose to acquire through the Bringhub Platform, by directly clicking on the content to be connected with a Retailer.  </p>
			<p>(ii) Retailers means entities that may offer their products or services for sale to Consumers through the Bringhub Platform by turning content in Publisher's sites, interactive and acquirable. </p>
			<p>(iii) Consumers means individuals who purchase goods and services from Retailers by clicking on Publisher's content, which activates the Bringhub Platform. Consumers' use of the Bringhub Platform is subject to an end user license agreement and privacy notice to be accepted before use. </p>
		<p>When contracting with Bringhub, Publishers and Retailers may be required to provide certain information, such as Name, URLs, Unique visitors per month, contact email address, contact phone number, banking information, and tax-ids.  Please refer to our Privacy Policy for additional details regarding the information we collect from you and what we do with that information.    You understand that your content as Publisher or as a Retailer (not including credit card information), may be transferred unencrypted through the Bringhub Platform and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit Card and payment information is always encrypted during transfer over networks.</p>
		<p>You may also provide additional, optional information so that We can provide You a more customized experience when using the Bringhub Platform &mdash;but, We will leave that decision with You.  Once You submit the required registration information, We alone will determine whether or not to approve Your proposed account.  If approved, You will be sent an e-mail detailing how to complete Your registration.  For so long as You use the account, You agree to provide true, accurate, current, and complete information which can be accomplished by logging into Your account and making relevant changes directly or contacting Us using the below contact information and We can make the changes for You.  And, if You forget Your password &mdash; no worries as We will happily send a password update to Your provided email address.</p>
		<p>You are responsible for complying with these Terms when You access this Website, whether directly or through any account that You may setup through or on this Website.  Because it is Your account, it is Your job to obtain and maintain all equipment and services needed for access to and use of This Website as well as paying related charges.  It is also Your responsibility to maintain the confidentiality of Your password(s), including any password of a third-party site that We may allow You to use to access this Website.  Should You believe Your password or security for This Website has been breached in any way, You must immediately notify Us</p>
		<h3>IV.  GENERAL USE AND BRINGHUB RIGHTS.</h3>
		<p>You must be 18 years or older or at least the age of majority in the jurisdiction where you reside or from which you use this Website and the Services.</p>
		<p>We invite You to use this Website for your internal business purposes ("Permitted Purposes").</p>
		<p>In these Terms we are granting You a limited, personal, non-exclusive and non-transferable license to use and to display the Materials; Your right to use the Materials is conditioned on Your compliance with these Terms.  You have no other rights in this Website or any Materials and You may not modify, edit, copy, reproduce, create derivative works of, reverse engineer, alter, enhance or in any way exploit any of this Website or Materials in any manner.  If You make copies of any of this Website while engaging in Permitted Purposes then We ask that You be sure to keep on the copies all of Our copyright and other proprietary notices as they appear on this Website.  </p>
		<p>Unfortunately, if You breach any of these Terms the above license will terminate automatically and You must immediately destroy any downloaded or printed Materials (and any copies thereof).</p>
		<p>We reserve the right to refuse service to anyone for any reason at any time.</p>
		<p>Bringhub does not pre-screen content from Publishers or Retailers and it is in your sole discretion to refuse or remove any of your content that is available via the Service.</p>
		<p>We reserve the right to provide our services to your competitors and make no promise of exclusivity in any particular market segment. You further acknowledge and agree that Bringhub employees and contractors may also be Bringhub customers/merchants and that they may compete with you, although they may not use your confidential information in doing so.</p>
		<p>In the event of a dispute regarding account ownership, we reserve the right to request documentation to determine or confirm account ownership. Documentation may include, but is not limited to, a scanned copy of your business license, government issued photo ID, the last four digits of the credit card on file, etc.</p>
		<p>Bringhub retains the right to determine, in our sole judgment, rightful account ownership and transfer an account to the rightful owner.  If we are unable to reasonably determine the rightful account owner, Bringhub reserves the right to temporarily disable an account until resolution has been determined between the disputing parties.</p>
		<h3>V. PAYMENTS.</h3>
		<p>If applicable, You agree to pay all applicable fees related to Your use of this Website and Our Services as these may be described in our Website from time to time and/or agreed separately in a separately executed written agreement.   We may suspend or terminate Your account and/or access to Our Services and this Website if Your payment is late and/or Your offered payment method cannot be processed.  By providing a payment method, You expressly authorize Us to charge the applicable fees on said payment method as well as taxes and other charges incurred thereto at regular intervals, all of which depend on Your particular contract for services and utilized services. </p>
		<p>We understand that You might cancel Your account, but please know that We will not provide any refund(s) and You will be responsible for paying any balance due on the account.  To make things less complicated, You agree that We may charge any unpaid fees to Your provided payment method and/or send You a bill for such unpaid fees.</p>
		<h3>VI.  ELECTRONIC COMMUNICATIONS.</h3>
		<p>By using the Website and/or the Services provided on or through the Website, You consent to receiving electronic communications from Us.  These electronic communications may include notices about applicable fees and charges, transactional information and other information concerning or related to the Website and/or Services provided on or through the Website.  These electronic communications are part of Your relationship with Us.  You agree that any notices, agreements, disclosures or other communications that We send You electronically will satisfy any legal communication requirements, including that such communications be in writing.</p>
		<h3>VII.  LINKS TO THIRD-PARTY SITES.</h3>
		<p>We think links are convenient, and We sometimes provide links on his Website to third-party websites.  We also may link third-party websites through the use of the Bringhub Platform.  If You use these links, You will leave this Website. We are not obligated to review any third-party websites that You link to from this Website, We do not control any of the third-party websites, and We are not responsible for any of the third-party websites (or the products, services, or content available through any of them). Thus, We do not endorse or make any representations about such third-party websites, any information, software, products, services, or materials found there or any results that may be obtained from using them. If You decide to access any of the third-party websites linked to from this Website, You do this entirely at Your own risk and You must follow the privacy policies and terms and conditions for those third-party websites.</p>
		<h3>VIII.  UNAUTHORIZED ACTIVITIES AND USE POLICY.</h3>
		<p>To be clear, We authorize Your use of the Bringhub Platform only for Permitted Purposes.  Any other use of the Bringhub Platform beyond the Permitted Purposes is prohibited and, therefore, constitutes unauthorized use of the Bringhub Platform.  This is because as between You and Us, all rights in the Bringhub Platform remain Our property (and/or that of our licensors).</p>
		<p>Unauthorized use of the Bringhub Platform may result in violation of various United States of America and international copyright laws.  Because We prefer keeping this relationship drama-free, We want to give You examples of things to avoid.  So, unless You have written permission from Us stating otherwise, You are not authorized to use the Bringhub Platform in any of the following ways (these are examples only and the list below is not a complete list of everything that You are not permitted to do):</p>
		<ol>
		<li>For any public or commercial purpose which includes use of the Bringhub Platform on another site or through a networked computer environment;</li>
		<li>In a manner that modifies, publicly displays, publicly performs, reproduces or distributes any of the Bringhub Platform;</li>
		<li>In a manner that violates any local, state, national, foreign, or international statute, regulation, rule, order, treaty, or other law;</li>
		<li>To stalk, harass, or harm another individual;</li>
		<li>To impersonate any person or entity or otherwise misrepresent Your affiliation with a person or entity;</li>
		<li>To interfere with or disrupt the Bringhub Platform or servers or networks connected to the Bringhub Platform;</li>
		<li>To use any data mining, robots, or similar data gathering or extraction methods in connection with the Bringhub Platform; or</li>
		<li>Attempt to gain unauthorized access to any portion of the Bringhub Platform or any other accounts, computer systems, or networks connected to the Bringhub Platform, whether through hacking, password mining, or any other means.</li>
		</ol>
		<p>You also agree and understand that as pertaining those sections of the Bringhub Platform that may allow you to post comments or upload or link content, You as the author are entirely responsible for the content of, and any harm resulting from, any content posted, linked, provided or uploaded by you ("Your Content"). That is the case regardless of whether Your Content in question constitutes text, graphics, audio files, information, products, services or computer software. By making Your Content available, you represent and warrant that:</p>
		<p>(i) The posting, downloading, copying, use and/or procurement of Your Content will not infringe the proprietary rights (intellectual or otherwise, including but not limited to the copyright, patent, trademark or trade secret rights), of any third party;</p>
		<p>(ii) Your Content does not contain or install any viruses, worms, malware, Trojan horses or other harmful or destructive content;</p>
		<p>(iii) Your Content is not spam, is not machine- or randomly-generated, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);</p>
		<p>(iv) Your Content does not contain threats or incite violence towards individuals or entities, and does not violate the privacy or publicity rights of any third party;</p>
		<p>(v) Your Content is not getting advertised via unwanted electronic messages such as spam links on newsgroups, email lists, other blogs and web sites, and similar unsolicited promotional methods;</p>
		<p>(vi) Your Content is not named in a manner that misleads your readers into thinking that you are another person or company. For example, your URL or name is not the name of a person other than yourself or company other than your own;</p>
		<p>(vii) You Content does not include racially, ethnically, obscene, sexually explicit or otherwise offensive language or use the Bringhub Platform to discuss, incite illegal activity or promote hatred against individuals or groups based on race, ethnic origin, religion, disability, gender, age, veteran status, sexual orientation, or gender identity.  </p>
		<p>You agree to hire attorneys to defend Us if You violate these Terms and that violation results in a problem for Us.  You also agree to pay any damages that We may end up having to pay as a result of Your violation.  You alone are responsible for any violation of these Terms by You.  We reserve the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by You and, in such case, You agree to cooperate with Our defense of such claim.</p>
		<p>We may, but have no obligation to, remove Content and accounts containing Content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party's intellectual property or these Terms.</p>
		<p>Verbal or written abuse of any kind (including threats of abuse or retribution) of any Bringhub customer, Bringhub employee, member, or officer will result in immediate account termination.</p>
		<h3>IX.  PROPRIETARY RIGHTS.</h3>
		<p>Bringhub®, SmartCart, are trademarks or registered trademarks of Bringhub Inc. and/or its affiliates and may not be used without express permission.</p>
		<p>Other trademarks, names and logos on this Website are the property of their respective owners.</p>
		<p>Unless otherwise specified in these Terms, all Materials, including the arrangement of them on this Website, and the Bringhub Platform in general are Our sole property,  Copyright © 2015, Bringhub, Inc.  All rights not expressly granted herein are reserved.  Except as otherwise required or limited by applicable law, any reproduction, distribution, modification, retransmission, or publication of any copyrighted material is strictly prohibited without the express written consent of the copyright owner or license.  </p>
		<p>We do not claim any intellectual property rights over the material you provide or link to the Bringhub service. All material you upload or link remains yours. You can remove your site, content or products from the Bringhub Platform at any time by deleting your account. This will also remove all content you have stored on the Bringhub Platform.</p>
		<p>By uploading or linking your Content, you agree: (a) to allow other internet users to view your Content; (b) to allow Bringhub to display and store your Content as necessary to provide you with the Services; and (c) that Bringhub can, at any time, review all the Content linked or submitted by you to its Services and determine if there is a violation of Section IX herein.</p>
		<p>By making your linked site or content public, you agree to allow others to view your Content. You are responsible for compliance of Content with any applicable laws or regulations.</p>
		<p>We will not disclose your confidential information to third parties, except as required in the course of providing our Services. Confidential information includes any materials or information provided by you to us which is not publicly known. Confidential information does not include information that: (a) was in the public domain at the time we received it; (b) comes into the public domain after we received it through no fault of ours; (c) we received from someone other than you without breach of our or their confidentiality obligations; or (d) we are required by law to disclose.</p>
		<h3>X.  INTELLECTUAL PROPERTY INFRINGEMENT.</h3>
		<p>We respect the intellectual property rights of others and encourage You to do the same. Accordingly, We have a policy of removing any content in our Website that violate intellectual property rights of others, suspending access to this Website (or any portion thereof) to any user who uses this Website in violation of someone's intellectual property rights, and/or terminating in appropriate circumstances the account of any user who uses this Website in violation of someone's intellectual property rights. </p>
		<p>Pursuant to Title 17 of the United States Code, Section 512, We have implemented procedures for receiving written notification of claimed copyright infringement and for processing such claims in accordance with such law. If You believe Your copyright or other intellectual property right is being infringed by a user of this Website, please provide written notice to Our Agent for notice of claims of infringement: Bringhub, Inc. Attn: DMCA Agent, 3221 Hutchison Ave., Suite H, Los Angeles, CA 90034, Email: dmca@bringhub.com.   </p>
		<p>To be sure the matter is handled immediately, Your written notice must: </p>
		<ol>
		<li>Contain Your physical or electronic signature;</li>
		<li>Identify the copyrighted work or other intellectual property alleged to have been infringed;</li>
		<li>Identify the allegedly infringing material in a sufficiently precise manner to allow Us to locate that material;</li>
		<li>Contain adequate information by which We can contact You (including postal address, telephone number, and e-mail address);</li>
		<li>Contain a statement that You have a good faith belief that use of the copyrighted material or other intellectual property is not authorized by the owner, the owner's agent or the law;</li>
		<li>Contain a statement that the information in the written notice is accurate; and</li>
		<li>Contain statement, under penalty of perjury, that You are authorized to act on behalf of the copyright or other intellectual property right owner. </li>
		</ol>
		<p>Unless the notice pertains to copyright or other intellectual property infringement, the Agent will be unable to address the listed concern.</p>
		<h4>Submitting a DMCA Counter-Notification</h4>
		<p>We will notify You that We have removed or disabled access to copyright-protected material that You provided, if such removal is pursuant to a validly received DMCA take-down notice. In response, You may provide Our Agent with a written counter-notification that includes the following information:</p>
		<ol>
		<li>Your physical or electronic signature;</li>
		<li>Identification of the material that has been removed or to which access has been disabled, and the location at which the material appeared before it was removed or access to it was disabled;</li>
		<li>A statement from You under the penalty of perjury, that You have a good faith belief that the material was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled; and</li>
		<li>Your name, physical address and telephone number, and a statement that You consent to the jurisdiction of a court for the judicial district in which Your physical address is located, or if Your physical address is outside of the United States, for any judicial district in which We may be located, and that You will accept service of process from the person who provided notification of allegedly infringing material or an agent of such person.</li>
		</ol>
		<h4>Termination of Repeat Infringers</h4>
		<p>We reserve the right, in Our sole discretion, to terminate the account or access of any user of this Website or Service who is the subject of repeated DMCA or other infringement notifications.  </p>
		<h3>XI.  DISCLAIMER OF WARRANTIES.</h3>
		<p>THE BRINGHUB PLATFORM IS PROVIDED "AS IS" AND "WITH ALL FAULTS" AND THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE BRINGHUB PLATFORM IS WITH YOU.</p>
		<p>WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND (EXPRESS, IMPLIED OR STATUTORY) WITH RESPECT TO THE BRINGHUB PLATFORM, WHICH INCLUDES BUT IS NOT LIMITED TO, ANY IMPLIED OR STATUTORY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE, TITLE, AND NON-INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS. </p>
		<p>THIS MEANS THAT WE DO NOT PROMISE YOU THAT THE BRINGHUB PLATFORM IS FREE OF PROBLEMS.  Without limiting the generality of the foregoing, We make no warranty that the Bringhub Platform will meet Your requirements or that the Bringhub Platform will be uninterrupted, timely, secure, or error free or that defects in the Bringhub Platform will be corrected. We make no warranty as to the results that may be obtained from the use of the Bringhub Platform or as to the accuracy or reliability of any information obtained through the Bringhub Platform. No advice or information, whether oral or written, obtained by You through the Bringhub Platform or from Us or Our subsidiaries/other affiliated companies shall create any warranty. We disclaim all equitable indemnities.</p>
		<h3>XII.  LIMITATION OF LIABILITY.</h3>
		<p>WE SHALL NOT BE LIABLE TO YOU FOR ANY DAMAGES RESULTING FROM YOUR DISPLAYING, COPYING, OR DOWNLOADING ANY MATERIALS TO OR FROM THIS WEBSITE NOR FOR ANY DAMAGES RESULTING FROM PERFORMANCE OF THE SERVICES.  IN NO EVENT SHALL WE BE LIABLE TO YOU FOR ANY INDIRECT, EXTRAORDINARY, EXEMPLARY, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES (INCLUDING LOSS OF DATA, REVENUE, PROFITS, USE OR OTHER ECONOMIC ADVANTAGE) HOWEVER ARISING, EVEN IF WE KNOW THERE IS A POSSIBILITY OF SUCH DAMAGE.</p>
		<h3>XIII.  LOCAL LAWS; EXPORT CONTROL.</h3>
		<p>We control and operate the Bringhub Platform from Our headquarters in the United States of America and the entirety of the Bringhub Platform may not be appropriate or available for use in other locations.  If You use the Bringhub Platform outside the United States of American, You are solely responsible for following applicable local laws.</p>
		<h3>XIV.  FEEDBACK.</h3>
		<p>Any submissions by You to Us (e.g., comments, questions, suggestions, materials &mdash; collectively, "Feedback") through any communication whatsoever (e.g., call, fax, email) will be treated as both non-confidential and non-proprietary.  You hereby assign all right, title, and interest in, and We are free to use, without any attribution or compensation to You, any ideas, know-how, concepts, techniques, or other intellectual property and proprietary rights contained in the Feedback, whether or not patentable, for any purpose whatsoever, including but not limited to, developing, manufacturing, having manufactured, licensing, marketing, and selling, directly or indirectly, products and services using such Feedback.  You understand and agree that We are not obligated to use, display, reproduce, or distribute any such ideas, know-how, concepts, or techniques contained in the Feedback, and You have no right to compel such use, display, reproduction, or distribution.</p>
		<h3>XV.  GENERAL.</h3>
		<p>We think direct communication resolves most issues &mdash; if We feel that You are not complying with these Terms, We will tell You.  We will even provide You with recommended necessary corrective action(s) because We value this relationship.</p>
		<p>However, certain violations of these Terms, as determined by Us, may require immediate termination of Your access to this Website without prior notice to You.  The Federal Arbitration Act, California state law and applicable U.S. federal law, without regard to the choice or conflicts of law provisions, will govern these Terms.  Foreign laws do not apply.  Except for disputes subject to arbitration as described above, any disputes relating to these Terms or this Website will be heard in the courts located in Los Angeles County, California. If any of these Terms are deemed inconsistent with applicable law, then such term(s) shall be interpreted to reflect the intentions of the parties, and no other terms will be modified.  By choosing not to enforced any of these Terms, We are not waiving Our rights.  These Terms are the entire agreement between You and Us and, therefore, supersede all prior or contemporaneous negotiations, discussions or agreements between Everyone about this Website.  The proprietary rights, disclaimer of warranties, representations made by You, indemnities, limitations of liability and general provisions shall survive any termination of these Terms.</p>
		<h3>XVI.  CALIFORNIA CONSUMER NOTICE.</h3>
		<p>Under California Civil Code Section 1789.3, California users are entitled to the following consumer rights notice: This Website and Service are provided by Bringhub, Inc., 3221 Hutchison Ave., Ste. H, Los Angeles, CA, 90034, USA.  If You have a question or complaint regarding the Bringhub Platform, please contact Customer Service at customerservice@bringhub.com.  You may also contact Us by writing to Bringhub, Inc., 3221 Hutchison Ave., Ste. H, Los Angeles, CA, 90034, USA. California residents may reach the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by post at 1625 North Market Blvd., Sacramento, CA 95834 or by telephone at (916) 445-1254 or (800) 952-5210 or Hearing Impaired at TDD (800) 326-2297 or TDD (916) 322-1700.</p>
		<h3>XVII.  CONTACT US.</h3>
<p>If You have any questions about these Terms or otherwise need to contact Us for any reason, You can reach Us at Bringhub, Inc., Customer Service Department, 3221 Hutchison Ave., Ste. H, Los Angeles, CA, 90034, USA. </p>

					</div>
				</div>


			<?php include 'includes/_footer.php'; ?>	
		</div>

<?php include 'includes/_foot.php'; ?>
